export const RefugeeData = [
    {
        id: 1,
        firstName: "Santosh",
        lastName: "Kola",
        email: "johndoe@example.com",
        phone: 45435546544,
        dateOfBirth: "1990-01-01",
        countryOfOrigin: "CountryName",
        currentLocation: "CurrentLocationName",
        language: "English",
        gender: "Male",
        imageUrl: 'https://talk.miraclesoft.com/avatar/skola2',
        caseAgentHistory: [
            { assignedDate: '2023-01-15', removedDate: '2023-05-10', agentName: 'Agent A' },
            { assignedDate: '2023-05-20', removedDate: '2023-08-01', agentName: 'Agent B' },
            { assignedDate: '2023-08-10', removedDate: null, agentName: 'Agent C' }, // Current agent
        ],
        joinedDate: '01-02-2024'
    },
    {
        id: 2,
        firstName: "Krishna",
        lastName: "Vedantam",
        email: "janesmith@example.com",
        phone: 354687454,
        dateOfBirth: "1985-05-10",
        countryOfOrigin: "AnotherCountry",
        currentLocation: "SomeOtherLocation",
        language: "Spanish",
        gender: "Male",
        imageUrl: 'https://talk.miraclesoft.com/avatar/kvedantam',
        caseAgentHistory: [
            { assignedDate: '2023-01-15', removedDate: '2023-05-10', agentName: 'Agent A' },
            { assignedDate: '2023-05-20', removedDate: '2023-08-01', agentName: 'Agent B' },
            { assignedDate: '2023-08-10', removedDate: null, agentName: 'Agent C' },
        ],
        joinedDate: '10-02-2023'
    },
    {
        id: 3,
        firstName: "Sai",
        lastName: "Karthik",
        email: "alicejohnson@example.com",
        phone: 1234567890,
        dateOfBirth: "1988-11-22",
        countryOfOrigin: "CountryA",
        currentLocation: "LocationA",
        language: "French",
        gender: "Male",
        imageUrl: 'https://talk.miraclesoft.com/avatar/snistala',
        caseAgentHistory: [
            { assignedDate: '2023-02-10', removedDate: '2023-06-20', agentName: 'Agent D' },
            { assignedDate: '2023-06-25', removedDate: '2023-09-15', agentName: 'Agent E' },
            { assignedDate: '2023-09-20', removedDate: null, agentName: 'Agent F' },
        ],
        joinedDate: '10-02-2024'
    },
    {
        id: 4,
        firstName: "Vinod",
        lastName: "Marupu",
        email: "bobbrown@example.com",
        phone: 9876543210,
        dateOfBirth: "1992-03-15",
        countryOfOrigin: "CountryB",
        currentLocation: "LocationB",
        language: "German",
        gender: "Male",
        imageUrl: 'https://talk.miraclesoft.com/avatar/vmarupu',
        caseAgentHistory: [
            { assignedDate: '2023-03-01', removedDate: '2023-07-01', agentName: 'Agent G' },
            { assignedDate: '2023-07-05', removedDate: '2023-10-01', agentName: 'Agent H' },
            { assignedDate: '2023-10-05', removedDate: null, agentName: 'Agent I' },
        ],
        joinedDate: '01-02-2024'
    },
    {
        id: 5,
        firstName: "John",
        lastName: "Vesli",
        email: "emilydavis@example.com",
        phone: 1122334455,
        dateOfBirth: "1995-07-20",
        countryOfOrigin: "CountryC",
        currentLocation: "LocationC",
        language: "Italian",
        gender: "Male",
        imageUrl: 'https://talk.miraclesoft.com/avatar/jchitri',
        caseAgentHistory: [
            { assignedDate: '2023-04-01', removedDate: '2023-08-01', agentName: 'Agent J' },
            { assignedDate: '2023-08-05', removedDate: '2023-11-01', agentName: 'Agent K' },
            { assignedDate: '2023-11-05', removedDate: null, agentName: 'Agent L' },
        ],
        joinedDate: '05-02-2024'
    },
    {
        id: 6,
        firstName: "Hema",
        lastName: "Marada",
        email: "michaelwilson@example.com",
        phone: 2233445566,
        dateOfBirth: "1983-12-05",
        countryOfOrigin: "CountryD",
        currentLocation: "LocationD",
        language: "Portuguese",
        gender: "Male",
        imageUrl: 'https://talk.miraclesoft.com/avatar/hmarada',
        caseAgentHistory: [
            { assignedDate: '2023-05-01', removedDate: '2023-09-01', agentName: 'Agent M' },
            { assignedDate: '2023-09-05', removedDate: '2024-01-01', agentName: 'Agent N' },
            { assignedDate: '2024-01-05', removedDate: null, agentName: 'Agent O' },
        ],
        joinedDate: '15-02-2024'
    },
    {
        id: 7,
        firstName: "Manikanta",
        lastName: "Chitikina",
        email: "sophiamartinez@example.com",
        phone: 6677889900,
        dateOfBirth: "1991-06-18",
        countryOfOrigin: "CountryE",
        currentLocation: "LocationE",
        language: "Chinese",
        gender: "Male",
        imageUrl: 'https://talk.miraclesoft.com/avatar/mchitikina',
        caseAgentHistory: [
            { assignedDate: '2023-06-01', removedDate: '2023-10-01', agentName: 'Agent P' },
            { assignedDate: '2023-10-05', removedDate: '2024-02-01', agentName: 'Agent Q' },
            { assignedDate: '2024-02-05', removedDate: null, agentName: 'Agent R' },
        ],
        joinedDate: '15-02-2023'
    },
    {
        id: 8,
        firstName: "James",
        lastName: "Taylor",
        email: "jamestaylor@example.com",
        phone: 3344556677,
        dateOfBirth: "1980-08-25",
        countryOfOrigin: "CountryF",
        currentLocation: "LocationF",
        language: "Arabic",
        gender: "Female",
        imageUrl: 'https://talk.miraclesoft.com/avatar/skola2',
        caseAgentHistory: [
            { assignedDate: '2023-07-01', removedDate: '2023-11-01', agentName: 'Agent S' },
            { assignedDate: '2023-11-05', removedDate: '2024-03-01', agentName: 'Agent T' },
            { assignedDate: '2024-03-05', removedDate: null, agentName: 'Agent U' },
        ],
        joinedDate: '01-02-2024'
    },
    {
        id: 9,
        firstName: "Olivia",
        lastName: "Anderson",
        email: "oliviaanderson@example.com",
        phone: 4455667788,
        dateOfBirth: "1993-09-10",
        countryOfOrigin: "CountryG",
        currentLocation: "LocationG",
        language: "Russian",
        gender: "Female",
        imageUrl: 'https://talk.miraclesoft.com/avatar/skola2',
        caseAgentHistory: [
            { assignedDate: '2023-08-01', removedDate: '2023-12-01', agentName: 'Agent V' },
            { assignedDate: '2023-12-05', removedDate: '2024-04-01', agentName: 'Agent W' },
            { assignedDate: '2024-04-05', removedDate: null, agentName: 'Agent X' },
        ],
        joinedDate: '08-02-2024'
    },
    {
        id: 10,
        firstName: "Liam",
        lastName: "Lee",
        email: "liamlee@example.com",
        phone: 5566778899,
        dateOfBirth: "1987-04-12",
        countryOfOrigin: "CountryH",
        currentLocation: "LocationH",
        language: "Japanese",
        gender: "Female",
        imageUrl: 'https://talk.miraclesoft.com/avatar/skola2',
        caseAgentHistory: [
            { assignedDate: '2023-09-01', removedDate: '2024-01-01', agentName: 'Agent Y' },
            { assignedDate: '2024-01-05', removedDate: '2024-05-01', agentName: 'Agent Z' },
            { assignedDate: '2024-05-05', removedDate: null, agentName: '' },
        ],
        joinedDate: '19-02-2024'
    },
    {
        id: 11,
        firstName: "Jeeva",
        lastName: "Kiran",
        email: "jeevakiran@example.com",
        phone: 8922266666,
        dateOfBirth: "1987-04-12",
        countryOfOrigin: "CountryH",
        currentLocation: "LocationH",
        language: "Japanese",
        gender: "Male",
        imageUrl: 'https://talk.miraclesoft.com/avatar/jadavani',
        caseAgentHistory: [
            { assignedDate: '2023-09-01', removedDate: '2024-01-01', agentName: 'Agent Y' },
            { assignedDate: '2024-01-05', removedDate: '2024-05-01', agentName: 'Agent Z' },
            { assignedDate: '2024-05-05', removedDate: null, agentName: '' },
        ],
        joinedDate: '28-02-2024'
    },
];
